version: 0.2

phases:
  install: 
    runtime-versions:
      nodejs: 20
  build:
    commands:
      - echo "Package & Dependicies are getting installed"
      - npm -f install
      
artifacts:
  files:
    - '**/*'
